name: wegotask
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  # STATE MANAGEMENT
  get: ^4.6.5

  # STORAGE
  get_storage: ^2.1.1
  shared_preferences: ^2.0.20

  # UI
  sizer: ^2.0.15
  cupertino_icons: ^1.0.2

  # FIREBASE
  firebase_crashlytics: ^3.0.17
  firebase_core: ^2.8.0 
  firebase_auth: ^4.3.0
  firebase_storage: ^11.0.16
  firebase_database: ^10.0.16
  # paginate_firestore: ^1.0.3+1
  cloud_firestore: ^4.4.5
  
  # CONNECTIVITY
  http: ^0.13.5
  connectivity_plus: ^3.0.2


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
